export const API_LOADING = 'API_LOADING';
export const API_SUCCESS = 'API_SUCCESS';
export const API_FAIL = 'API_FAIL';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';
export const DISPLAY_NOTIFICATION = 'DISPLAY_NOTIFICATION';

export const OPEN_MENU = 'OPEN_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const COMPILE = 'COMPILE';
export const RUN = 'RUN';

export const ADD_GUIDE = 'ADD_GUIDE';
export const EDIT_GUIDE = 'EDIT_GUIDE';
export const GET_GUIDES = 'GET_GUIDES';
export const GET_GUIDE = 'GET_GUIDE';
export const DELETE_GUIDE = 'DELETE_GUIDE';
export const SEARCH_GUIDES = 'SEARCH_GUIDES';

export const CREATE_GUIDE = 'CREATE_GUIDE';
export const ADD_EXERCISE_TO_GUIDE = 'ADD_EXERCISE_TO_GUIDE';

export const ADD_EXERCISE = 'ADD_EXERCISE';
export const EDIT_EXERCISE = 'EDIT_EXERCISE';
export const GET_EXERCISES = 'GET_EXERCISES';
export const GET_EXERCISE = 'GET_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';

export const UPLOAD_RESOLUTION = 'UPLOAD_RESOLUTION';
export const SEND_RESOLUTION = 'SEND_RESOLUTION';
export const GET_LAST_RESOLUTION = 'GET_LAST_RESOLUTION';

export const GET_COURSES = 'GET_COURSES';
export const SUBSCRIBE_COURSE = 'SUBSCRIBE_COURSE';
export const UNSUBSCRIBE_COURSE = 'UNSUBSCRIBE_COURSE';
