export const API_LOADING = 'API_LOADING';
export const API_SUCCESS = 'API_SUCCESS';
export const API_FAIL = 'API_FAIL';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';
export const DISPLAY_NOTIFICATION = 'DISPLAY_NOTIFICATION';

export const OPEN_MENU = 'OPEN_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const COMPILE = 'COMPILE';
export const RUN = 'RUN';

export const ADD_GUIDE = 'ADD_GUIDE';
export const EDIT_GUIDE = 'EDIT_GUIDE';
export const UPDATE_GUIDE = 'UPDATE_GUIDE';
export const GET_GUIDES = 'GET_GUIDES';
export const GET_ACTIVE_GUIDES = 'GET_ACTIVE_GUIDES';
export const GET_GUIDE = 'GET_GUIDE';
export const DELETE_GUIDE = 'DELETE_GUIDE';
export const SEARCH_GUIDES = 'SEARCH_GUIDES';
export const GET_GUIDE_REPORT = 'GET_GUIDE_REPORT';

export const CREATE_GUIDE = 'CREATE_GUIDE';
export const ADD_EXERCISE_TO_GUIDE = 'ADD_EXERCISE_TO_GUIDE';
export const DELETE_EXERCISE_FROM_GUIDE = 'DELETE_EXERCISE_FROM_GUIDE';
export const EDIT_EXERCISE_FROM_GUIDE = 'EDIT_EXERCISE_FROM_GUIDE';
export const SELECT_EXERCISE_TO_EDIT = 'SELECT_EXERCISE_TO_EDIT';

export const ADD_EXERCISE = 'ADD_EXERCISE';
export const EDIT_EXERCISE = 'EDIT_EXERCISE';
export const GET_EXERCISES = 'GET_EXERCISES';
export const GET_EXERCISE = 'GET_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';

export const UPLOAD_RESOLUTION = 'UPLOAD_RESOLUTION';
export const SEND_RESOLUTION = 'SEND_RESOLUTION';
export const GET_LAST_RESOLUTION = 'GET_LAST_RESOLUTION';
export const GET_RESOLUTION_HISTORY = 'GET_RESOLUTION_HISTORY';

export const ADD_USER = 'ADD_USER';
export const EDIT_USER = 'EDIT_USER';
export const DELETE_USER = 'DELETE_USER';
export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const FILTER_USERS = 'FILTER_USERS';

export const GET_ROLES = 'GET_ROLES';

export const GET_COURSE = 'GET_COURSE';
export const GET_COURSES = 'GET_COURSES';
export const GET_SUBSCRIBED_COURSES = 'GET_SUBSCRIBED_COURSES';
export const SUBSCRIBE_COURSE = 'SUBSCRIBE_COURSE';
export const UNSUBSCRIBE_COURSE = 'UNSUBSCRIBE_COURSE';

export const ADD_SIGNATURE = 'ADD_SIGNATURE';
export const EDIT_SIGNATURE = 'EDIT_SIGNATURE';
export const DELETE_SIGNATURE = 'DELETE_SIGNATURE';
export const GET_SIGNATURES = 'GET_SIGNATURES';
export const GET_SIGNATURE = 'GET_SIGNATURE';

export const SET_ROUTE_FLOW = 'SET_ROUTE_FLOW';
export const SET_TEST_TO_EDIT = 'SET_TEST_TO_EDIT';
